### ISSUE TITLE
logstream-leader ingress error

### ISSUE THREAD

**Issue by bdalpe** [criblio/helm-charts#92]
```
error retrieving endpoint for logstream-leader. no endpoints for target port 9000 in server logstream-leader
```

**Comment by Kavinraja-G** [comment]
@bdalpe -- With `/*` as prefix I'm facing the below error when deploying with AWS ALB ingress controller.
`Failed build model due to ingress: test/test-leader: prefix path should not contain wildcards: /*`

Looks like the ingress defaults to `pathType` as `Prefix` which will not work with wildcards. So we need to override it with `ImplementationSpecific`

Refer issue [here](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2066)

Can we include that field customizable?

**Comment by bdalpe** [comment]
Hi @Kavinraja-G, I addressed this in #82. You can set the prefix desired in your Helm values file. This chart will continue to use `/*` as the default for backwards compatibility.

```
ingress:
  prefix: /
```

**Comment by brittonhayes** [comment]
Hey @bdalpe! 👋 I believe that @Kavinraja-G was hoping that the setting `pathType` could be provided as a helm value so users could specify other pathTypes such as `ImplementationSpecific`.

I don't believe PR #82 solved that request.

Would you be able to add support for customizing pathType?

[Reference](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/)

**Comment by bdalpe** [comment]
I see. Happy to surface this setting into the values.

**Comment by brittonhayes** [comment]
Thanks so much! Appreciate your fast reply and all your work to maintain this repository.
